print(f"not False = {not False}")
print(f"not True = {not True}\n\n", "*" * 20)
print(f"False OR False = {False or False}")
print(f"True OR True = {True or True}")
print(f"True OR False = {True or False}")
print(f"False OR True = {False or True}\n\n", "*" * 20)
print(f"True AND True = {True and True}")
print(f"True AND False = {True and False}")
print(f"False AND True = {False and True}")
print(f"False AND False = {False and False}\n\n", "*" * 20)
print(f"NOT(False OR False) = {not(False or False)}")
print(f"NOT(True OR True) = {not(True or True)}")
print(f"NOT(True OR False) = {not(True or False)}")
print(f"NOT(False OR True) = {not(False or True)}\n\n", "*" * 20)
print(f"NOT(True AND True) = {not(True and True)}")
print(f"NOT(True AND False) = {not(True and False)}")
print(f"NOT(False AND True) = {not(False and True)}")
print(f"NOT(False AND False) = {not(False and False)}\n\n", "*" * 20)
print(f"1 == 0 {1 == 0}")
print(f"1 == 1 {1 == 1}")
print(f"0 == 1 {0 == 1}")
print(f"0 == 0 {0 == 0}\n\n", "*" * 20)
print(f"1 == 0 {1 == 0}")
print(f"1 == 1 {1 == 1}")
print(f"0 == 1 {0 == 1}")
print(f"0 == 0 {0 == 0}\n\n", "*" * 20)


